# Generated by Django 3.2.12 on 2025-07-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_usermodel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
