# Generated by Django 3.2.12 on 2025-07-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_remove_usermodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_name',
        ),
    ]
